#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : python-neutronclient
Version  : 6.10.0
Release  : 39
URL      : http://tarballs.openstack.org/python-neutronclient/python-neutronclient-6.10.0.tar.gz
Source0  : http://tarballs.openstack.org/python-neutronclient/python-neutronclient-6.10.0.tar.gz
Source99 : http://tarballs.openstack.org/python-neutronclient/python-neutronclient-6.10.0.tar.gz.asc
Summary  : CLI and Client Library for OpenStack Networking
Group    : Development/Tools
License  : Apache-2.0
Requires: python-neutronclient-bin
Requires: python-neutronclient-python3
Requires: python-neutronclient-license
Requires: python-neutronclient-python
Requires: Babel
Requires: Sphinx
Requires: cliff
Requires: debtcollector
Requires: iso8601
Requires: keystoneauth1
Requires: netaddr
Requires: openstackdocstheme
Requires: os-client-config
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-keystoneclient
Requires: reno
Requires: requests
Requires: simplejson
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the python-neutronclient package.
Group: Binaries
Requires: python-neutronclient-license

%description bin
bin components for the python-neutronclient package.


%package license
Summary: license components for the python-neutronclient package.
Group: Default

%description license
license components for the python-neutronclient package.


%package python
Summary: python components for the python-neutronclient package.
Group: Default
Requires: python-neutronclient-python3

%description python
python components for the python-neutronclient package.


%package python3
Summary: python3 components for the python-neutronclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-neutronclient package.


%prep
%setup -q -n python-neutronclient-6.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536587748
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/python-neutronclient
cp LICENSE %{buildroot}/usr/share/doc/python-neutronclient/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/neutron

%files license
%defattr(-,root,root,-)
/usr/share/doc/python-neutronclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
